export const SIGN_UPUSER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGN_UPUSER_FAILURE = 'SIGNUP_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';


